### ISSUE TITLE
Runtime error in the data pre-processing (open3d) 

### ISSUE THREAD

**Issue by r03943158** [facebookresearch/ContrastiveSceneContexts#16]
Hi, I am trying to run the data pre-processing on the scanNetv2. 
However, when the script (preprocess.sh) running the function pcd.points = o3d.utility.Vector3dVector(xyz) in compute_full_overlapping.py, there is a runtime error without any information. I found that the size of numpy array is (276497, 7)in the pcd file generated by point_cloud_extractor.py. 

How should I fix the shape to (n, 3)?

Thank you.

**Comment by Sekunde** [comment]
hi, 
thanks for pointing it out. I make a pull request which should fix it.

**Comment by r03943158** [comment]
It works fine after updating. Thank you.
