### ISSUE TITLE
Issue on preparing scannet downstream data

### ISSUE THREAD

**Issue by sjtuchenye** [facebookresearch/ContrastiveSceneContexts#18]
Sorry but I can not find path  'downstream/semseg/lib/datasets/preprocessing/scannet' in this repo. I find scannet.py to preprocess data in PointContrast repo, but I get the error ''PosxiPath' object has no attribute 'write''. I do not know what is wrong.

**Comment by Hiusam** [comment]
I cannot find scannet.py in downstream/semseg/datasets/preprocessing/

**Comment by Sekunde** [comment]
@Hiusam hi, thanks for pointing out, it is supposed to be collect_indoor3d_data.py
