### ISSUE TITLE
Training data split 

### ISSUE THREAD

**Issue by ahme0307** [facebookresearch/ContrastiveSceneContexts#26]
Thank you for the interesting work. Would it be possible for you to share the training data split filenames or script for generating for ScanNet and Shapenet?

![image](https://user-images.githubusercontent.com/1628008/146385006-57137bcc-daa7-43c0-b53d-a1cb4eb4e722.png)
![image](https://user-images.githubusercontent.com/1628008/146385192-1657d0a9-d2b7-41e7-baa3-4eb255e60c06.png)
Thanks in advance,

**Comment by Sekunde** [comment]
Hi, thanks for your interest in our work!

Please refer to scannet data-efficient benchmark for the splits: http://kaldir.vc.in.tum.de/scannet_benchmark/data_efficient/documentation

Unfortunately, I don't have the splits for ShapeNet.

**Comment by ahme0307** [comment]
Hi Ji, 

Thanks for the response. 
I will close the issue.
