### ISSUE TITLE
Preprocess S3DIS data

### ISSUE THREAD

**Issue by Hiusam** [facebookresearch/ContrastiveSceneContexts#29]
Hi, I downloaded the S3DIS data and unzipped the data, but it seems like the file structure of the dataset does not match your preprocessing code. The structure is as follows:
```S3DIS
├── ReadMe.txt
├── Stanford3dDataset_v1.2_Aligned_Version.mat
├── Stanford3dDataset_v1.2_Aligned_Version.zip
├── Stanford3dDataset_v1.2.mat
└── Stanford3dDataset_v1.2.zip
```
Can you share your file structure and give me some suggestions? 
Thank you very much!

**Comment by Sekunde** [comment]
Hi, you can unzip the Stanford3dDataset_v1.2.zip to a folder, the data should be there

**Comment by Hiusam** [comment]
Thank you very much.
