### ISSUE TITLE
How long it will take to train downstream tasks?

### ISSUE THREAD

**Issue by iris0329** [facebookresearch/ContrastiveSceneContexts#3]
Hi, 

thanks for opening source so briliant work!

It said in  [PointContrast/issues/12](https://github.com/facebookresearch/PointContrast/issues/12) that 
> It takes around 40 hours to train scripts/ddp_local.sh (60000 iters with batch size 32) on 8 GPUs (like V100)

I am curious about how long it will take to train downstream tasks, such as semantic segmentation？

Best

**Comment by s9xie** [comment]
@iris0329 Thanks for the question - the downstream task training is much faster, e.g. for semantic segmentation tasks on ScanNet, it takes around 9 hours with 8 V100 GPUs.

**Comment by iris0329** [comment]
Thank you ~
