### ISSUE TITLE
Train split for limited scene reconstructions

### ISSUE THREAD

**Issue by YilmazKadir** [facebookresearch/ContrastiveSceneContexts#37]
Do you use the first 1%, 5%, 10%, 20% of the data when you fine-tune the network on ScanNet semantic segmentation for limited reconstruction case, or do you randomly shuffle the data first? If so, do you avoid splitting subscenes that are generated in the same scene to train and validation?

**Comment by Sekunde** [comment]
We split out 1%,5%,10%,20% from the official train split, which already splits sub-scenes from val.
If I remember correctly, we took the first 1%, 5%, 10%, 20% of the data; but you can verify that by checking e.g., if 1% scenes are all included in 5% scenes.

**Comment by YilmazKadir** [comment]
Thanks for quick reply. I think I have found the scenes that you used at ScanNet Data Efficient web page:
http://kaldir.vc.in.tum.de/scannet_benchmark/data_efficient/documentation#submission-policy
For those who also wonders here is the zip file that contains scene IDs:
[scenes.zip](https://github.com/facebookresearch/ContrastiveSceneContexts/files/8929936/scenes.zip)
