### ISSUE TITLE
question about NMS in instance segmentation

### ISSUE THREAD

**Issue by Dingry** [facebookresearch/ContrastiveSceneContexts#39]
Hi, thanks for your code release. I have a question about the nms code [here](https://github.com/facebookresearch/ContrastiveSceneContexts/blob/83515bef4754b3d90fc3b3a437fa939e0e861af8/downstream/insseg/lib/test.py#L65). It seems that it only removes some proposals predicted in [10, 12, 16] classes, not like a regular NMS where the proposal score is utilized for proposal ranking and the iou overlap between proposals are computed to remove redundant proposals?

**Comment by Sekunde** [comment]
Thanks for raising it up. That is due to debugging purpose and you can just comment it out.

**Comment by Dingry** [comment]
Thanks for you reply. Do you mean that the NMS is not needed in final inference?

**Comment by Sekunde** [comment]
Hi, NMS (this implementation is just a selection between the two sets of clustering results, not really NMS)is only used when enabling dual set clustering, and we do not use the dual set clustering for the paper setup; it is only used when submitting to the ScanNet benchmark.

**Comment by Dingry** [comment]
Thanks for your reply. My questions are addressed.
