### ISSUE TITLE
Which epoch of pretrained model is used for downstream tasks?

### ISSUE THREAD

**Issue by mutianxu** [facebookresearch/ContrastiveSceneContexts#40]
Dear authors,

Thanks for your great work!

**Which epoch** of models **during ScanNet pertaining,** would be later used for downstream tasks to get better performance?

Thanks,
Mino

**Comment by Sekunde** [comment]
Hi, thanks for your interest!
We do not ablate the pre-training epochs, and we use 100k iterations normally. There are some variances, however, we observe that training more can bring better performance in general (e.g, compare 100k iterations with 20k)
