### ISSUE TITLE
About instance loss for PointGroup

### ISSUE THREAD

**Issue by Gofinge** [facebookresearch/ContrastiveSceneContexts#42]
Hi, thanks for your research; it's really inspired me a lot. I have a question about your reproduced version of PointGroup, since I am trying to add instance segmentation support to my codebase.

The [original PointGroup](https://github.com/dvlab-research/PointGroup/blob/a41c2cd22808861f0d4986b2825875c10bb661e5/model/pointgroup/pointgroup.py#L473:L493) adds an `instance loss` after a preparing epoch, but the reproduced version of CSC only contains a `seg loss` and two `offset loss`, and I am curious about the reason. Does it because the `instance loss` can not promote the performance?

**Comment by Sekunde** [comment]
Hi there, the initial purpose is just to have a clean and simple instance segmentation method we can work with, we didn't intend to exactly reproduce the PointGroup. For instance loss, I am not sure whether it helps, I assume it would further improve the performance as you add it.

**Comment by Gofinge** [comment]
I see. Thanks for your quick response!
