### ISSUE TITLE
Visual color selection

### ISSUE THREAD

**Issue by yhyang-myron** [facebookresearch/ContrastiveSceneContexts#47]
Thanks for your excellent work!
I have observed that the visualization colors in your work are very attractive. Could you please introduce your visualization methods and color selection?
Thank you!!

**Comment by Sekunde** [comment]
Hi, thanks for your interests! We use Mitsuba2 for rendering point cloud, check these out: https://github.com/mitsuba-renderer/mitsuba2 and https://github.com/chrdiller/mitsuba-visualize

**Comment by yhyang-myron** [comment]
Thanks!!
