### ISSUE TITLE
Confuse about compute_partitions_fast in shape context.py

### ISSUE THREAD

**Issue by mahaoxiang822** [facebookresearch/ContrastiveSceneContexts#6]
pretrain/contrastive_scene_contexts/lib/shape_context.py Line 89-90

`maskUp = rel_trans[:,:,2] > self.r1`
`maskDown = rel_trans[:,:,2] > self.r1`

maskUp and maskDown are same.   Is there existing some mistakes?

**Comment by Sekunde** [comment]
hi, 
thanks for pointing it out, it was due to some copy-paste error during the code refactoring, we will fix it soon.
